### ISSUE TITLE
[git] 2.37.3 doesn't build

### ISSUE THREAD

**Issue by therealnv6** [purlinux/pur-repo#2]
make[1]: Leaving directory '/var/db/installed/git/files/git-2.37.3/Documentation'
make -C Documentation install-info
make[1]: Entering directory '/var/db/installed/git/files/git-2.37.3/Documentation'
make[2]: Entering directory '/var/db/installed/git/files/git-2.37.3'
make[2]: 'GIT-VERSION-FILE' is up to date.
make[2]: Leaving directory '/var/db/installed/git/files/git-2.37.3'
    DB2TEXI user-manual.texi
/bin/sh: line 1: docbook2x-texi: command not found
make[1]: *** [Makefile:380: user-manual.texi] Error 127
make[1]: Leaving directory '/var/db/installed/git/files/git-2.37.3/Documentation'
make: *** [Makefile:3299: install-info] Error 2

**Comment by pcranaway** [comment]
use code blocks idiot

**Comment by pcranaway** [comment]
Looks like we need `docbook2x`. Will work on it when I can.

**Comment by therealnv6** [comment]
> Looks like we need `docbook2x`. Will work on it when I can.

Not sure what docbook2x is. I feel like there's a way to exclude it from the installation considering it doesn't compile on Gentoo either (while I have Git on Gentoo).

**Comment by pcranaway** [comment]
> > Looks like we need `docbook2x`. Will work on it when I can.
> 
> Not sure what docbook2x is. I feel like there's a way to exclude it from the installation considering it doesn't compile on Gentoo either (while I have Git on Gentoo).

Could you try running make without the docs target?
