### ISSUE TITLE
download large packages as archives instead of git repositories

### ISSUE THREAD

**Issue by pcranaway** [purlinux/pur-repo#3]
Large packages may take longer to download through git because it downloads the entire commit history. For example: git's `.git` directory is 209MB. The entire directory (including source code) is 259MB which means that the source code only takes 50MB. 

We could make downloading packages way faster if we preferred to download the packages as an archive (say, as a tar.gz) instead of a git repository.

**Comment by therealnv6** [comment]
We don't download through git, our packages should all use curl in the first place to remove the dependency for git.
